version: "3.3"

services:
  database:
    image: mysql:8.0
    container_name: toudeuk-database
    environment:
      MYSQL_ROOT_PASSWORD: toudeuk
      MYSQL_DATABASE: toudeuk
      MYSQL_USER: toudeuk
      MYSQL_PASSWORD: toudeuk
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - toudeuk-db:/var/lib/mysql

  db-admin:
    container_name: db-admin
    image: phpmyadmin/phpmyadmin
    ports:
      - "5000:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: toudeuk
    restart: always

  cache-database:
    image: redis
    container_name: toudeuk-cache-database
    ports:
      - "6379:6379"
    entrypoint: redis-server --requirepass toudeuk --maxmemory 1gb


  # !! Ngrinder 설정 나중에 서버를 분리하면 스프링 서버가 돌아가지 않는 다른 서버에서 해야함 !!
  controller:
    container_name: ngrinder-controller
    image: ngrinder/controller:3.5.5
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
  agent:
    container_name: ngrinder-agent
    image: ngrinder/agent:3.5.5
    restart: always
    links:
      - controller

volumes:
  toudeuk-db: